owner: rda-run
repo: upptime
sites:
  - name: Vault
    url: https://vault.rda.run/v1/sys/health
  - name: Passwords
    url: https://passwords.rda.run/alive
  - name: Links
    url: https://link.rda.run
  - name: Clear Address
    url: https://clear-address.rda.run/v1/rdeavila@gmail.com
  - name: Mirrors
    url: https://mirrors.rda.run/almalinux
  - name: Mirror Report Service
    url: https://mirrors-report.rda.run
  - name: RPM
    url: https://rpm.rda.run
  - name: Link Shortener
    url: https://l.rda.run
  - name: CSPRNG Service
    url: https://csprng.rda.run/v1/api
  - name: Knowledge base
    url: https://docs.rda.run
  - name: Home
    url: https://rda.run
status-website:
  cname: status.rda.run
  logoUrl: https://rda.run/icon/bimi.svg
  name: rda.run
  introTitle: "**rda.run** services"
  favicon: https://rda.run/icon/favicon.ico
  faviconSvg: https://rda.run/icon/bimi.svg
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://rda.run
    - title: Knowledge Base
      href: https://docs.rda.run
assignees:
  - rdeavila
